#!/bin/bash

set -euo pipefail; # safe mode
shopt -s dotglob; # include hidden files mode
cd -P -- "$(dirname "$0")"

# Imports
source ../helpers/gpg
source ../helpers/stow

# Load config variables
source ./config

echo "Linking dotfiles to $HOME..."
link_dotfile_dirs  . $HOME