#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode
cd -P -- "$(dirname "$0")"

# Imports
source ../helpers/stow

# Load config variables
source ./config

if [ -z "${1+x}" ] ; then
  echo "Unlinking dotfiles from $HOME..."
  unlink_dotfile_dirs . "$HOME"
else
  echo "Unlinking "$1" fromo $HOME..."
  unlink_dotfiles "$1" "$HOME"
fi
