#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode
cd -P -- "$(dirname "$0")"

# Imports
source ../helpers/stow

# Load config variables
source ./config

if [ -z "${1+x}" ] ; then
  echo "Linking new dotfiles to $HOME..."
  link_dotfile_dirs . "$HOME"
else
  echo "Linking dotfiles from "$1" to $HOME..."
  link_dotfiles "$1" "$HOME"
fi
