#!/bin/bash

mkdir -p "$CONFIG_DIR"

# Usage: read_config name description
read_config() {
  if test -f "$CONFIG_DIR/$1" ; then
    cat "$CONFIG_DIR/$1"
  else
    description="$2"
    [ ! -z ${3+x} ] && description="$description (default $3)"
    read -rp "Enter $description: " value
    if [ -z "$value" ] && [ ! -z ${3+x} ] ; then
      echo "$3"
    else
      echo "$value"
    fi
  fi
}

# Usage: read_config name default
read_config_cache() {
  if test -f "$CONFIG_DIR/$1" ; then
    cat "$CONFIG_DIR/$1"
  else
    echo "$2"
  fi
}

# Usage: read_config name value [required]
update_config() {
  rm -f "$CONFIG_DIR/$1"
  if [[ $? -eq 0 ]] ; then
    echo "$2" > "$CONFIG_DIR/$1"
  elif [ -z ${3+x} ] ; then 
    exit 1
  fi
}

clear_config() {
  if [ ! -z ${3+x} ] ; then
    rm -r "$CONFIG_DIR"
  else
    rm "$CONFIG_DIR/$1"
  fi
}
