#!/bin/bash

set -o noclobber  # Enable overwriting existing files

# Usage: decrypt_recursive direction
align_file_permissions() {
  files=$(find -L "$1" -maxdepth 100 -type f -name '*.gpg')
  for encrypted in $files ; do
    decrypted=${encrypted%.gpg}
    [ "$1" == "encrypt" ] && chmod --reference="$decrypted" -- "$encrypted"
    [ "$1" == "decrypt" ] && chmod --reference="$encrypted" -- "$decrypted"
  done
}

# Usage: decrypt_recursive path
decrypt_recursive() {
  files=$(find -L "$1" -maxdepth 100 -type f -name '*.gpg')
  for encrypted in $files ; do
    decrypted=${encrypted%.gpg}
    gpg --decrypt-files "$encrypted"
    chmod --reference="$encrypted" -- "$decrypted"
  done
}

# Usage: encrypt_recursive path recipient
encrypt_recursive() {
  files=$(find -L "$1" -maxdepth 100 -type f ! -name '*.gpg' ! -name '.stow-local-ignore')
  for decrypted in $files ; do
    encrypted="$decrypted.gpg"
    gpg --yes --recipient "$2" --encrypt-files "$decrypted"
    chmod --reference="$decrypted" -- "$encrypted"
  done
}
