#!/bin/bash

set -o noclobber  # Enable overwriting existing files

# Usage: decrypt_recursive path
decrypt_recursive() {
  find -L "$1" -maxdepth 100 -type f -name '*.gpg' \
    | xargs --no-run-if-empty -- \
      gpg --batch --decrypt-files
}

# Usage: encrypt_recursive path recipient
encrypt_recursive() {
  find -L "$1" -maxdepth 100 -type f ! -name '*.gpg' ! -name '.stow-local-ignore' \
    | xargs --no-run-if-empty -- \
      gpg --batch --yes --recipient "$2" --encrypt-files
}
