#!/bin/bash

distro=$(lsb_release -si)

# INTERNAL # Usage: install instructions [...name]
install_fallback() {
  instructions="$1"
  shift
  case $distro in
    *Ubuntu*)
      ! dpkg -s "$@" &> /dev/null && \
      ! sudo apt-get -y install "$@" &> /dev/null && \
      echo "$instructions" && return 1;
  esac
  return 0;
}

# Usage: install [...name]
install() {
  echo "Checking for $@:"
  if install_fallback "    ❌ Please install $* manually" "$@" ; then
    echo "    ✅ installed"
    return 0
  else
    return 1
  fi
}

# Usage: path_exists name path
path_exists() {
  name="$1"; shift
  dest="$1"; shift

  echo "Checking for $name:"
  if [ -d "$dest" ] || [ -f "$dest" ] ; then
    echo "    ✅ installed"
    return 0
  else
      echo "    ❌ not installed"
    return 1
  fi
}

# Usage: install_git name repo dest [...args]
install_git() {
  name="$1"; shift
  repo="$1"; shift
  dest="$1"; shift
  args="$@"

  echo "Checking for $name:"
  if [ -d "$dest" ] || git clone $args "$repo" "$dest" ; then
    echo "    ✅ installed"
    return 0
  else
    echo "    ❌ Please clone $repo to \"$dest\" manually"
    return 1
  fi
}