#!/bin/bash

# Usage: link_dotfile_dirs path target
link_dotfile_dirs() {
  find -L "$1" -maxdepth 1 -type d ! \( -name '.*' \) -printf '%P\0' \
    | xargs -t0 --max-args=1 --no-run-if-empty -- \
      stow -v -R --target="$2"
}

# Usage: link_dotfile_dirs path target_base
link_dotfile_dirs_keep_tree() {
  find -L "$1" -maxdepth 1 -type d ! \( -name '.*' \) -printf '%P\n' \
    | xargs --no-run-if-empty --replace="{}" -- \
      stow -v --no-folding -R --target="$2/{}" "{}"
}

# Usage: link_dotfiles path target
link_dotfiles() {
  stow -v -R --target="$2" "$1"
}

# Usage: unlink_dotfile_dirs path target
unlink_dotfile_dirs() {
  find -L "$1" -maxdepth 1 -type d ! \( -name '.*' \) -printf '%P\0' \
    | xargs -t0 --max-args=1 --no-run-if-empty -- \
      stow -v -D --target="$2"
}

# Usage: unlink_dotfile_dirs path target_base
unlink_dotfile_dirs_keep_tree() {
  find -L "$1" -maxdepth 1 -type d ! \( -name '.*' \) -printf '%P\0' \
    | xargs -t0 -I --max-args=1 --no-run-if-empty -- \
      stow -v -D --target="$2/{}"
}

# Usage: unlink_dotfiles path target
unlink_dotfiles() {
  stow -v -D --target="$2" "$1"
}
