#!/bin/bash

[[ "$0" == */config ]] && cd -P -- "$(dirname "$0")"

export CONFIG_DIR="$PWD/.setup/main"

source ./helpers/config

if [[ ! -z ${1+x} && "$1" == "clear" ]] ; then
  if [[ ! -z ${2+x} && "$2" == "all" ]] ; then
    clear_config
    ./dotfiles/config clear
    ./secure/config clear
  elif [ ! -z ${2+x} ] ; then
    clear_config "$2"
  else
    clear_config
  fi
fi

profiles=$(find -L profiles -maxdepth 1 -type d ! -name 'template' ! -name '.setup' -printf '%P ')
DOTFILE_PROFILE=""

while [ ! -z ${DOTFILE_PROFILE+x} ] ; do
  DOTFILE_PROFILE=$(read_config \
    dotfile_profile \
    "your active dotfile profile [$profiles]")
  if [[ " ${profiles} " =~ " ${DOTFILE_PROFILE} " ]]; then
    update_config profiles "$DOTFILE_PROFILE" true
    break;
  else
    echo "Invalid Profile \"$DOTFILE_PROFILE\" [$profiles]!"
  fi
done

echo "Using Config:"
echo "    dotfile profile: $DOTFILE_PROFILE"
echo

# Load subconfigs of specified
if [[ ! -z ${1+x} && "$1" == "all" ]] ; then
  echo "Updating dotfile config"
  ./dotfiles/config
  echo
  echo "Updating secure config"
  echo
  ./secure/config
fi

export DOTFILE_PROFILE
