#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Includes
source ./helpers/gpg

# Load config variables
source ./config

dir="$(dirname "$1")"
out="$2"
if [[ "$out" == profiles/secure* ]] ; then
  "$out"/import $1 $2
elif [[ "$out" == profiles/* ]] ; then
  "$out"/dotfiles/import $1 $2
elif [[ "$out" == global/secure/* ]] ; then
  secure/import $1 $2
elif [[ "$out" == global/* ]] ; then
  dotfiles/import $1 $2
elif [[ ! -z "$DOTFILE_PROFILE" && "$out" == secure/* ]] ; then
  profiles/"$DOTFILE_PROFILE"/secure/import $1 $2
elif [[ ! -z "$DOTFILE_PROFILE" ]] ; then
  profiles/"$DOTFILE_PROFILE"/dotfiles/import $1 $2
elif [[ "$out" == secure/* ]] ; then
  secure/import $1 $2
else
  dotfiles/import $1 $2
fi
