#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Includes
source ./helpers/software

# Install required packages
install stow
install_fallback "Please follow https://code.visualstudio.com/docs/setup/linux to install code" code

# Bootstrap initial configs
stow -v bootstrap

# Install dotfiles
migrations/install
dotfiles/install
secure/install