#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Includes
source ./helpers/software

# Load config variables
source ./config

# Install required packages
install stow
install code
install coreutils
echo

# install_fallback "Please follow https://code.visualstudio.com/docs/setup/linux to install code" code

# Bootstrap initial configs
stow -v bootstrap --target=$HOME

# Install dotfiles
migrations/install

if [ ! -z ${DOTFILE_PROFILE+x} ] ; then
  cd profiles/"$DOTFILE_PROFILE" && git submodule update --init
  ./install
else
  secure/install
  dotfiles/install
fi
