#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Includes
source ./helpers/software

# Load config variables
source ./config

# Install required packages
install stow gpg coreutils
install_fallback "Please follow https://code.visualstudio.com/docs/setup/linux to install code" code

# Bootstrap initial configs
stow -v bootstrap

# Install dotfiles
migrations/install
secure/install
dotfiles/install

# Install Profiles
other_profiles=${DOTFILE_PROFILES//$DOTFILE_DEFAULT_PROFILE/}
for $profile in $other_profiles ; do
  cd profiles/"$profile" && git submodule update --init
  ,/install && cd ../..
done

cd profiles/"$DOTFILE_DEFAULT_PROFILE" && git submodule update --init
./install # Overlay current profile