#!/bin/bash

source ./config

previous_profile="$CONFIG_DIR"

rm -f "$CONFIG_DIR/dotfile_profile"

./config

if [ "$previous_profile" != "$DOTFILE_PROFILE" ] ; then
  "./profiles/$previous_profile/unlink"
fi

./update
