#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Pull Changes
git pull

# Load config variables
source ./config

migrations/update
secure/update
dotfiles/update

# Update Profiles
other_profiles=${DOTFILE_PROFILES//$DOTFILE_DEFAULT_PROFILE/}
for $profile in $other_profiles ; do
  cd profiles/"$profile" && git submodule update --init
  ./update && cd ../..
done

cd profiles/"$DOTFILE_DEFAULT_PROFILE" && git submodule update --init
./update # Overlay current profile