#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Pull Changes
git pull

# Load config variables
source ./config

migrations/update

if [ -z ${DOTFILE_PROFILE+x} ] ; then
  cd profiles/"$DOTFILE_PROFILE" && git submodule update --init
  ./update
else
  secure/update
  dotfiles/update
fi