#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Load config variables
source ./config

migrations/update
secure/update
dotfiles/update

# Update Profiles
other_profiles=${DOTFILE_PROFILES//$DOTFILE_DEFAULT_PROFILE/}
for $profile in $other_profiles ; do
  profiles/"$profile"/update
done

profiles/"$DOTFILE_DEFAULT_PROFILE"/update # Overlay current profile