#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Includes
source ../../helpers/software

# Run setup script local
if [ -f setup ] ; then
  source setup
  echo
fi

# Load config variables
source ./config

# Install dotfiles
test -f migrations && migrations/install
secure/install
dotfiles/install
