#!/bin/bash

set -euo pipefail; shopt -s failglob # safe mode

cd -P -- "$(dirname "$0")"

# Load config variables
source ./config

test -f migrations && migrations/update
dotfiles/update
secure/update
