#!/bin/bash

cd -P -- "$(dirname "$0")"

export CONFIG_DIR="$PWD/../.setup/secure"

source ../helpers/config

if [[ ! -z ${1+x} && "$1" == "clear" ]] ; then
  if [[ ! -z ${2+x} ]] ; then
    clear_config "$2"
  else
    clear_config
  fi
fi

GPG_KEY_ID=$(read_config \
  gpg_key_id \
  "your gpg key id for decryption")
gpg -k "$GPG_KEY_ID" \
  | update_config gpg_key_id "$GPG_KEY_ID" true

echo "Using Config:"
echo "    gpg key id: $GPG_KEY_ID"
echo

export GPG_KEY_ID
