#!/bin/bash

[[ "$0" == */config ]] && cd -P -- "$(dirname "$0")"

export CONFIG_DIR="$PWD/../.setup/secure"

source ../helpers/config

if [[ ! -z ${1+x} && "$1" == "clear" ]] ; then
  if [[ ! -z ${2+x} ]] ; then
    echo "Clearing secure config \"$2\""
    clear_config "$2"
  else
    echo "Clearing all secure configs..."
    clear_config
  fi
  echo
fi

GPG_KEY_ID=$(read_config \
  gpg_key_id \
  "your gpg key ids for decryption")
echo "$GPG_KEY_ID" | xargs printf -- '-k %s\n' | xargs gpg \
  | update_config gpg_key_id "$GPG_KEY_ID" true

echo "Using Config:"
echo "    gpg key id: $GPG_KEY_ID"
echo

export GPG_KEY_ID
