#!/bin/bash

set -euo pipefail # safe mode
shopt -s dotglob  # include hidden files mode
cd -P -- "$(dirname "$0")"

# Imports
source ../helpers/gpg

# Load config variables
source ./config

echo "Encryptring files..."
readarray -d '' profiles < <(find -L . -maxdepth 1 -type d ! \( -name '.*' \))
for profile in $profiles ; do
  encrypt_recursive "$profile" "$GPG_KEY_ID"
  echo "    Successfully Encrypted $profile"
done
