#!/bin/bash

set -euo pipefail # safe mode
shopt -s dotglob  # include hidden files mode
cd -P -- "$(dirname "$0")"

# Imports
source ../helpers/gpg
source ../helpers/stow

# Load config variables
source ./config

dir="$(dirname "$1")"
out="${2#secure/}"

mkdir -p "$out/$dir"
if ! test -f "$out/.stow-local-ignore" ; then
  # Create stow ignore file to omit *.gpg files
  ln -s ../.stow-local-ignore "$out/.stow-local-ignore"
fi

echo "Copying files from $HOME/$1 to secure/$out/$dir..."
cp -r "$HOME/$1" "$out/$dir/"
mkdir -p "../dotfiles/$out"               # create dotfile directory if not exists
if test -f "../dotfiles/$out/$1"; then
  # Copy over existing unsecured dotfiles
  cp -rf "../dotfiles/$out/$1" "$out/$dir/"
else
  # Copy over dotfiles from home dir
  cp -rf "$HOME/$1" "$out/$dir/"
fi
echo

echo "Encrypting files in secure/$out/$dir..."
encrypt_recursive "$out/$dir/" "$GPG_KEY_ID"
echo

echo "Clean up unsecure dotfiles"
if test -f "../dotfiles/$out/$1"; then
  rm -rf "../dotfiles/$out/$1"
else
  rm -rf "$HOME/$1"
fi
echo

echo "Linking dotfiles from secure/$out to dotfiles/$out..."
link_dotfiles "$out" "../dotfiles/$out"
echo

../dotfiles/update "$out"
